version: '3.8'

services:
  backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    image: task5-backend
    expose:
      - "5252"
    networks:
      - app-network

  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    image: softy-pinko-front-end:task5
    expose:
      - "9000"
    depends_on:
      - backend
    networks:
      - app-network

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    image: task5-proxy
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
